### ISSUE TITLE
GPRSelect plugin

### ISSUE THREAD

**Issue by TamaMcGlinn** [glacambre/.dotfiles#1]
Hi Ghjuvan,
I guess you haven't seen my reply to [your post on the neovim discourse](https://neovim.discourse.group/t/lsp-project-specific-settings/541) regarding selecting .gpr project files; I made a neovim plugin, [GPRSelector](https://github.com/TamaMcGlinn/nvim-lsp-gpr-selector), to do just that. Please try it out and give me feedback.

**Comment by glacambre** [comment]
Hi Tama,

I saw your reply on Discourse, your plugin looks pretty cool and I even shared it with some of my colleagues who use Neovim :). It seems to work great (although [this looks a bit weird](https://github.com/TamaMcGlinn/nvim-lsp-gpr-selector/blob/21ae246096b66a5fd0a7e7ea25c13905823df554/lua/gpr_selector.lua#L94) - perhaps we should ask the people who work on nvim's LSP if there is a better way?), thank you for building it!

**Comment by TamaMcGlinn** [comment]
Unfortunately, the LSP author has not shown much interest in Ada-related contributions. https://github.com/neovim/nvim-lspconfig/pull/1693

I can try asking about this specifically but I'm sure it will be up to Ada users to debug this issue and submit a PR.

I've turned your comment [into an issue here](https://github.com/TamaMcGlinn/nvim-lsp-gpr-selector/issues/3), feel free to open up anything else there if/when it comes up.

I am currently working on an expansion of the plugin to automatically grab the correct .gpr in alire projects, including the correct GPR_PROJECT_PATH env. (as a workaround in the meantime, I just do `eval $(alr printenv)` and then launch nvim)
